// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// corCosine_cpp
arma::mat corCosine_cpp(const arma::mat& x, Nullable<arma::mat> y);
RcppExport SEXP _PIPET_corCosine_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Nullable<arma::mat> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(corCosine_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dist_to_cor_inplace
NumericVector dist_to_cor_inplace(NumericVector x);
RcppExport SEXP _PIPET_dist_to_cor_inplace(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_to_cor_inplace(x));
    return rcpp_result_gen;
END_RCPP
}
// cor_to_dist_inplace
NumericVector cor_to_dist_inplace(NumericVector x);
RcppExport SEXP _PIPET_cor_to_dist_inplace(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cor_to_dist_inplace(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PIPET_corCosine_cpp", (DL_FUNC) &_PIPET_corCosine_cpp, 2},
    {"_PIPET_dist_to_cor_inplace", (DL_FUNC) &_PIPET_dist_to_cor_inplace, 1},
    {"_PIPET_cor_to_dist_inplace", (DL_FUNC) &_PIPET_cor_to_dist_inplace, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_PIPET(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
