# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_to_cor_inplace <- function(x) {
    .Call('_PIPET_dist_to_cor_inplace', PACKAGE = 'PIPET', x)
}

cor_to_dist_inplace <- function(x) {
    .Call('_PIPET_cor_to_dist_inplace', PACKAGE = 'PIPET', x)
}

