# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corCosine_cpp <- function(x, y = NULL) {
    .Call('_PIPET_corCosine_cpp', PACKAGE = 'PIPET', x, y)
}

dist_to_cor_inplace <- function(x) {
    .Call('_PIPET_dist_to_cor_inplace', PACKAGE = 'PIPET', x)
}

cor_to_dist_inplace <- function(x) {
    .Call('_PIPET_cor_to_dist_inplace', PACKAGE = 'PIPET', x)
}

